package com.accounting.entity;

import lombok.Data;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 税务处理视图对象
 * 包含业务来源信息
 * 
 * @author Accounting Platform
 * @version 1.0.0
 */
@Data
public class TaxHandlingVO {
    /**
     * 主键ID
     */
    private Long id;
    
    /**
     * 税种类型
     */
    private String taxType;
    
    /**
     * 纳税期间
     */
    private String taxPeriod;
    
    /**
     * 税额
     */
    private BigDecimal taxAmount;

    /**
     * 缴税日期
     */
    private Date paymentDate;
    
    /**
     * 状态（0-未申报，1-已申报，2-已缴）
     */
    private Integer status;
    
    /**
     * 业务来源类型（SALARY-工资发放，SALES-销售，PURCHASE-采购等）
     */
    private String businessType;
    
    /**
     * 业务来源ID（关联的业务单据ID）
     */
    private Long businessId;
    
    /**
     * 关联的凭证ID（缴税后自动生成）
     */
    private Long journalEntryId;
    
    /**
     * 是否系统自动生成
     */
    private Boolean autoGenerated;
    
    /**
     * 业务来源信息（如：采购订单编号、销售订单编号、员工姓名等）
     */
    private String businessSourceInfo;
}


