package com.accounting.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 税务处理实体类
 * 
 * @author Accounting Platform
 * @version 1.0.0
 */
@Data
@TableName("tax_handling")
public class TaxHandling {
    /**
     * 主键ID
     */
    @TableId(type = IdType.AUTO)
    private Long id;
    
    /**
     * 税种类型
     */
    private String taxType;
    
    /**
     * 纳税期间
     */
    private String taxPeriod;
    
    /**
     * 税额
     */
    private BigDecimal taxAmount;

    /**
     * 缴税日期
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date paymentDate;
    
    /**
     * 状态（0-未申报，1-已申报，2-已缴）
     */
    private Integer status;
    
    /**
     * 业务来源类型（SALARY-工资发放，SALES-销售，PURCHASE-采购等）
     */
    private String businessType;
    
    /**
     * 业务来源ID（关联的业务单据ID）
     */
    private Long businessId;
    
    /**
     * 关联的凭证ID（缴税后自动生成）
     */
    private Long journalEntryId;
    
    /**
     * 是否系统自动生成（true-系统生成，false-手动新增，现在只允许系统生成）
     */
    private Boolean autoGenerated;
}
