package com.accounting.service.impl;

import com.accounting.entity.*;
import com.accounting.mapper.*;
import com.accounting.service.TaxHandlingService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * 税务处理服务实现类
 * 
 * @author Accounting Platform
 * @version 1.0.0
 */
@Service
public class TaxHandlingServiceImpl extends ServiceImpl<TaxHandlingMapper, TaxHandling> implements TaxHandlingService {

    @Autowired
    private TaxHandlingMapper taxHandlingMapper;
    
    @Autowired
    private PurchaseOrderMapper purchaseOrderMapper;
    
    @Autowired
    private SalesOrderMapper salesOrderMapper;
    
    @Autowired
    private EmployeeMapper employeeMapper;
    
    @Autowired
    private EmployeeExpenseMapper employeeExpenseMapper;

    /**
     * 保存税务处理记录（禁止手动新增，只能通过业务自动生成）
     * 
     * @param taxHandling 税务处理对象
     * @return 保存后的对象
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public TaxHandling saveTaxHandling(TaxHandling taxHandling) {
        // 禁止手动新增，只能通过业务自动生成
        if (taxHandling.getAutoGenerated() == null || !taxHandling.getAutoGenerated()) {
            throw new RuntimeException("税务记录只能通过业务自动生成，不能手动新增");
        }
        taxHandlingMapper.insert(taxHandling);
        return taxHandling;
    }

    /**
     * 更新税务处理记录（系统生成的记录可以更新，但有限制）
     * 
     * @param taxHandling 税务处理对象
     * @return 更新后的对象
     */
    @Override
    @Transactional(rollbackFor = Exception.class)
    public TaxHandling updateTaxHandling(TaxHandling taxHandling) {
        // 查询原记录
        TaxHandling oldTax = taxHandlingMapper.selectById(taxHandling.getId());
        if (oldTax == null) {
            throw new RuntimeException("税务记录不存在");
        }
        
        // 系统生成的记录可以更新状态等信息，但不能修改核心业务数据
        // 只允许更新状态、缴税日期等字段
        TaxHandling updateTax = new TaxHandling();
        updateTax.setId(taxHandling.getId());
        if (taxHandling.getStatus() != null) {
            updateTax.setStatus(taxHandling.getStatus());
        }
        if (taxHandling.getPaymentDate() != null) {
            updateTax.setPaymentDate(taxHandling.getPaymentDate());
        }
        
        taxHandlingMapper.updateById(updateTax);
        return taxHandlingMapper.selectById(taxHandling.getId());
    }

    @Override
    public boolean declareTax(Long id) {
        TaxHandling taxHandling = new TaxHandling();
        taxHandling.setId(id);
        taxHandling.setStatus(1); // 已申报
        return taxHandlingMapper.updateById(taxHandling) > 0;
    }

    @Override
    public boolean payTax(Long id) {
        TaxHandling taxHandling = new TaxHandling();
        taxHandling.setId(id);
        taxHandling.setStatus(2); // 已缴款
        taxHandling.setPaymentDate(new java.util.Date());
        return taxHandlingMapper.updateById(taxHandling) > 0;
    }
    
    /**
     * 获取业务来源信息
     * 
     * @param taxHandling 税务处理对象
     * @return 业务来源信息描述
     */
    public String getBusinessSourceInfo(TaxHandling taxHandling) {
        if (taxHandling.getBusinessType() == null || taxHandling.getBusinessId() == null) {
            return "未知来源";
        }
        
        String businessType = taxHandling.getBusinessType();
        Long businessId = taxHandling.getBusinessId();
        
        try {
            switch (businessType) {
                case "PURCHASE":
                    PurchaseOrder purchaseOrder = purchaseOrderMapper.selectById(businessId);
                    if (purchaseOrder != null) {
                        return "采购订单：" + purchaseOrder.getOrderNumber();
                    }
                    break;
                case "SALES":
                    SalesOrder salesOrder = salesOrderMapper.selectById(businessId);
                    if (salesOrder != null) {
                        return "销售订单：" + salesOrder.getOrderNumber();
                    }
                    break;
                case "SALARY":
                    Employee employee = employeeMapper.selectById(businessId);
                    if (employee != null) {
                        return "员工工资：" + employee.getEmployeeName();
                    }
                    break;
                case "EXPENSE":
                    EmployeeExpense expense = employeeExpenseMapper.selectById(businessId);
                    if (expense != null) {
                        return "员工费用：" + expense.getExpenseNo();
                    }
                    return "员工费用：" + businessId;
                default:
                    return businessType + "：" + businessId;
            }
        } catch (Exception e) {
            // 忽略异常，返回默认信息
        }
        
        return businessType + "：" + businessId;
    }
}